In [11]:
import tensorflow as tf
import tensorflow.lite as tflite
import numpy as np
from PIL import Image

In [12]:
# Get the path to the image file
file_path = "./data/Plant Disease/test/test/CornCommonRust1.JPG"
# Load the TensorFlow Lite model
interpreter = tflite.Interpreter(model_path='./assets/plants_disease.tflite')
interpreter.allocate_tensors()

In [13]:
# Get input and output details
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

print(input_details)

[{'name': 'serving_default_mobilenetv2_1.00_224_input:0', 'index': 0, 'shape': array([  1, 224, 224,   3]), 'shape_signature': array([ -1, 224, 224,   3]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]


In [14]:
# Preprocess the image
img = Image.open(file_path).resize((224, 224))
print("akakaka", img)
img = np.array(img)
print("akiakiaki", img)
img = img.astype(np.float32) / 255.0
print("adjaksdjas",img)

akakaka <PIL.Image.Image image mode=RGB size=224x224 at 0x186874F7FD0>
akiakiaki [[[ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]
  ...
  [ 4  3  2]
  [ 6  2  1]
  [ 6  2  0]]

 [[ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]
  ...
  [ 4  3  2]
  [ 6  2  1]
  [ 6  2  0]]

 [[ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]
  ...
  [ 4  3  2]
  [ 4  3  1]
  [ 4  3  0]]

 ...

 [[71 67 27]
  [81 79 37]
  [83 83 40]
  ...
  [ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]]

 [[87 80 42]
  [90 85 45]
  [84 82 40]
  ...
  [ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]]

 [[88 80 43]
  [97 92 53]
  [98 94 54]
  ...
  [ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]]]
adjaksdjas [[[0.01176471 0.01176471 0.01176471]
  [0.01176471 0.01176471 0.01176471]
  [0.01176471 0.01176471 0.01176471]
  ...
  [0.01568628 0.01176471 0.00784314]
  [0.02352941 0.00784314 0.00392157]
  [0.02352941 0.00784314 0.        ]]

 [[0.01176471 0.01176471 0.01176471]
  [0.01176471 0.01176471 0.01176471]
  [0.01176471 0.01176471 0.01176471]
  ...
  [0.01568628 0.01176471 0.00784314]
  

In [15]:
# Set the input tensor
input_data = np.expand_dims(img, axis=0)
input_data = input_data.astype(input_details[0]['dtype'])

In [16]:
interpreter.set_tensor(input_details[0]['index'], input_data)

In [17]:
# Run inference
interpreter.invoke()

In [18]:
output_tensor = interpreter.get_tensor(output_details[0]['index'])
predictions = np.squeeze(output_tensor)

In [19]:
import os

# Get the folder names as class labels
label_names = sorted(os.listdir('./data/Plant Disease/New Plant Diseases Dataset/train'))

# Postprocess the output
predicted_label_index = np.argmax(output_tensor)
predicted_label = label_names[predicted_label_index]

print("Predicted label:", predicted_label)

Predicted label: Corn_(maize)___Common_rust_
